Add in Spark compat 128-bit divide
NVIDIA/spark-rapids-jni pull request #506
Opened 2022-08-25 16:49 UTC by revans2

This adds in an operator that can do a Spark compatible 128-bit divide. It is not as complicated as the multiply is, because the bugs in Divide I could deal with in the plugin instead of here.

The performance is also similar to multiply, but for some reason the CPU divide is a lot worse. So much so that I spent half an hour doing a benchmark on the CPU for a Divide of Decimal(9,0) by Decimal(9,0), but then only estimated how long the Decimal(38, 0) version would take, because it was not good.  The numbers I have right now are.

precision | GPU | CPU | speedup
-- | -- | -- | --
9 | 11,225 | 1,900,344 | 169.30
10 | 13,593 |   | N/A
18 | 13,595 |   | N/A
19 | 10,010 |   | N/A
32 | 9,900 |   | N/A
38 | 9,879 | 3,529,412 - estimated | 357.26 - estimated

These are for the query
```
spark.time(spark.range(10000000000L).selectExpr("CAST(id as DECIMAL($PRECISION,0))").selectExpr("id / id as p").filter("p > 0").count())
```

There are also a few fixes to some bugs that I found in rounding, divide itself, and in computing powers of 10. These didn't show up in the multiply because the rounding and divide bugs were not able to be hit by how multiply works. For the powers of 10, it was close enough to the real value that when doing a divide the answer didn't change, but it was not good enough for doing a multiply with it.

2022-08-25 16:49 UTC, revans2 commented
build

2022-08-26 02:34 UTC, hyperbolic2346 requested changes
Nits around const. I'm not 100% all of them will work out as some may be changed. I'd be careful about reuse of a variable for the sake of not having to make another though.
```
bool tmp = calc();
do_thing(tmp);
tmp = calc2();
do_another_thing(tmp);
```
isn't as good as
```
auto const thing1_tmp = calc();
do_thing(thing1_tmp);
auto const thing2_tmp = calc2();
do_another_thing(thing2_tmp);
```

Bonus points for names other than `thing1_tmp` and `thing2_tmp`. :)

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +  __int128_t double_remainder = r << 1;
```suggestion
  __int128_t const double_remainder = r << 1;
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +      __int128_t first_div_scale_divisor = pow_ten(first_div_precision).as_128_bits();
```suggestion
      auto const first_div_scale_divisor = pow_ten(first_div_precision).as_128_bits();
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +        __int128_t scale_mult = pow_ten( -exponent).as_128_bits();
```suggestion
        auto const scale_mult = pow_ten( -exponent).as_128_bits();
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +      __int128_t scale_divisor = pow_ten(exponent).as_128_bits();
```suggestion
      auto const scale_divisor = pow_ten(exponent).as_128_bits();
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +  __device__ __int128_t operator()(cudf::size_type i) const {
```suggestion
  __device__ __int128_t operator()(cudf::size_type const i) const {
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +      divmod256 first_div_result = divide(n, d);
```suggestion
      divmod256 const first_div_result = divide(n, d);
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +      __int128_t scale_divisor = pow_ten(n_shift_exp).as_128_bits();
```suggestion
      auto const scale_divisor = pow_ten(n_shift_exp).as_128_bits();
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +      chunked256 result = divide_and_round(first_div_result.quotient, scale_divisor);
```suggestion
      auto const result = divide_and_round(first_div_result.quotient, scale_divisor);
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +      chunked256 scale_mult = pow_ten(38);
```suggestion
      auto const scale_mult = pow_ten(38);
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +      result = round_from_remainder(result, second_div_result.remainder, first_div_r, d);
```suggestion
      auto const first_div_result = divide(n, d);
      auto const first_div_r(first_div_result.remainder);

      //now we have to multiply each of these by how much is left
      int remaining_exp = (-n_shift_exp) - 38;
      scale_mult = pow_ten(remaining_exp);
      auto result = multiply(first_div_result.quotient, scale_mult);
      first_div_r = multiply(first_div_r, scale_mult);

      // Now do a second divide on what is left
      auto const second_div_result = divide(first_div_r, d);
      result.add(second_div_result.quotient);

      // and finally round
      result = round_from_remainder(result, second_div_result.remainder, first_div_r, d);
```

2022-08-26 02:34 UTC, hyperbolic2346 commented on src/main/cpp/src/decimal_utils.cu
> +        chunked256 scale_mult = pow_ten(-n_shift_exp);
```suggestion
        auto const scale_mult = pow_ten(-n_shift_exp);
```

2022-08-26 14:10 UTC, revans2 commented
build

2022-08-26 14:10 UTC, revans2 commented
@hyperbolic2346 and @jlowe please take another look

2022-08-26 14:34 UTC, jlowe approved these changes

2022-08-26 14:35 UTC, jlowe commented
build

2022-08-26 18:05 UTC, hyperbolic2346 approved these changes

2022-08-26 18:07 UTC, merged